"""Router package for model-routing experiments."""

from .arena import (
    ApproachResult,
    bundled_head_to_head,
    head_to_head,
    project_latency_ms,
)
from .baseline import (
    baseline_cost_usd,
    baseline_model_for_task,
    model_router_pick,
    model_router_summary,
    score_single_call_arm,
    single_call_baseline_arms,
)
from .budget import BudgetDecision, BudgetGate
from .classify import Classifier, RuleBasedClassifier, classify_task
from .experiment import (
    Experiment,
    ExperimentResult,
    list_experiments,
    load_experiment,
    run_experiment,
)
from .foundry_live import (
    DEFAULT_API_VERSION,
    FOUNDRY_LIVE_ENV_VARS,
    AzureModelRouterClient,
    FoundryConfig,
    MeasuringRouterClient,
    RecordedRouterClient,
    RouterOutcome,
    capture_recorded_usage,
    load_dotenv_file,
    load_recorded_usage,
    measured_router_summary,
    normalize_model_name,
)
from .foundry_router import (
    FOUNDRY_ROUTER_ENV_VARS,
    FoundryModelRouter,
    azure_router_choice_client,
    capture_recorded_choices,
    live_router_summary,
    load_recorded_choices,
    summary_from_choices,
)
from .metrics import (
    ExperimentMetrics,
    FoundryMetricsEmitter,
    JsonlMetricsStore,
    MetricSink,
    extract_experiment_metrics,
    fanout_stats,
    record_experiment_metrics,
)
from .offline import (
    load_signal_fixture,
    load_task_prompts,
    load_workload,
    route_task,
    route_tasks,
    summarize_traces,
    synthesize_shared_signals,
    synthesize_signals,
    synthesize_task_signals,
)
from .pipeline import (
    ReplayReport,
    batch_route_payload,
    find_samples_root,
    format_eval_report,
    format_regression_report,
    format_replay_json,
    format_replay_text,
    load_default_pricing,
    load_policy,
    policy_summary,
    regression_report,
    resolve_paths,
    resolve_policy_path,
    route_payload,
    run_bundled_replay,
    run_evals,
    run_replay,
    run_route_once,
    summarize_by_class,
)
from .pricing import PricingTable, TokenRates
from .profile import TaskProfile, profile_task, stratify_traces
from .select import SelectionAttempt, SelectionResult, compare_select, ordered_select
from .signals import (
    OFFLINE_SIGNAL_KINDS,
    SignalBundle,
    SignalSource,
    assert_offline_ledger_kind,
    fixture_signal_source,
    resolve_signal_source,
    synth_signal_source,
)
from .spotlight import Spotlight, select_spotlight, spotlight_for
from .trace import build_trace

__version__ = "0.1.0"

__all__ = [
    "ApproachResult",
    "BudgetDecision",
    "BudgetGate",
    "Classifier",
    "AzureModelRouterClient",
    "DEFAULT_API_VERSION",
    "Experiment",
    "ExperimentMetrics",
    "ExperimentResult",
    "FOUNDRY_LIVE_ENV_VARS",
    "FOUNDRY_ROUTER_ENV_VARS",
    "FoundryConfig",
    "FoundryMetricsEmitter",
    "FoundryModelRouter",
    "JsonlMetricsStore",
    "MeasuringRouterClient",
    "MetricSink",
    "OFFLINE_SIGNAL_KINDS",
    "PricingTable",
    "ReplayReport",
    "RecordedRouterClient",
    "RouterOutcome",
    "RuleBasedClassifier",
    "SelectionAttempt",
    "SelectionResult",
    "SignalBundle",
    "SignalSource",
    "Spotlight",
    "TokenRates",
    "TaskProfile",
    "__version__",
    "assert_offline_ledger_kind",
    "baseline_cost_usd",
    "baseline_model_for_task",
    "bundled_head_to_head",
    "head_to_head",
    "project_latency_ms",
    "model_router_pick",
    "model_router_summary",
    "score_single_call_arm",
    "single_call_baseline_arms",
    "batch_route_payload",
    "build_trace",
    "azure_router_choice_client",
    "capture_recorded_choices",
    "capture_recorded_usage",
    "classify_task",
    "compare_select",
    "extract_experiment_metrics",
    "fanout_stats",
    "find_samples_root",
    "fixture_signal_source",
    "format_eval_report",
    "format_regression_report",
    "format_replay_json",
    "format_replay_text",
    "list_experiments",
    "live_router_summary",
    "load_default_pricing",
    "load_dotenv_file",
    "load_experiment",
    "load_policy",
    "load_recorded_choices",
    "load_recorded_usage",
    "load_signal_fixture",
    "load_task_prompts",
    "load_workload",
    "measured_router_summary",
    "normalize_model_name",
    "ordered_select",
    "policy_summary",
    "profile_task",
    "record_experiment_metrics",
    "regression_report",
    "resolve_paths",
    "resolve_policy_path",
    "resolve_signal_source",
    "route_payload",
    "route_task",
    "route_tasks",
    "run_bundled_replay",
    "run_evals",
    "run_experiment",
    "run_replay",
    "run_route_once",
    "select_spotlight",
    "spotlight_for",
    "summarize_by_class",
    "summarize_traces",
    "summary_from_choices",
    "stratify_traces",
    "synth_signal_source",
    "synthesize_shared_signals",
    "synthesize_signals",
    "synthesize_task_signals",
]
