#!/usr/bin/env python3
"""Emit English ``.en.svg`` variants of the 03D result charts.

The charts in ``docs/assets/03d/*.svg`` are generated by
``build_03d_dashboard.py`` with Korean axis/legend/annotation labels baked in.
They are shared assets referenced by both the Korean and the English manual, so
an English page that embeds the bare ``.svg`` shows Korean chart labels to an
English reader (even though its Markdown alt-text is already English).

This script derives an English-labelled ``<name>.en.svg`` beside each Korean
``<name>.svg`` by substituting a fixed, audited Korean -> English label map.
It reads the *committed* Korean SVGs (it does **not** regenerate them, so the
Korean charts stay byte-identical and visually unchanged), and it fails loudly
if any chart carries a Korean run that the map does not cover — so a future
relabelling in ``build_03d_dashboard.py`` cannot silently leak Korean onto the
English pages. English wording follows the canonical English page
``docs/en/manual/routing-measured-results.md`` (pass rate, cost-per-pass, sub-cent, full
precision, graded cells, percentage-point wording spelled out, the section headings).

Run ``python scripts/localize_03d_svgs.py`` after regenerating the charts.
Numbers, model names and identifiers are never translated.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "docs" / "assets" / "03d"
CHARTS = (
    "arm-cost-comparison",
    "cost-vs-quality-scatter",
    "backend-distribution",
)

# Audited Korean -> English label map. Each key is a full text-node string that
# appears verbatim (and uniquely) in a committed chart; values keep every
# number, model name, symbol (× — · → ↓ –) and honesty term intact.
LABELS: dict[str, str] = {
    # arm-cost-comparison.svg
    "실험 12 실측 · arm별 총비용 — 통과율 · cost-per-pass":
        "Experiment 12, measured · total cost per arm — pass rate · cost-per-pass",
    "24 tasks × n=3 = 288 cells · measured=true · directional · "
    "금액 2자리(서브센트 4자리) · 절감은 풀정밀도":
        "24 tasks × n=3 = 288 cells · measured=true · directional · amounts shown "
        "to 2 places (sub-cent to 4) · savings at full precision",
    (
        "실험 12: router-cost는 direct-premium 대비 95.2% 저렴(풀정밀도), "
        "통과율 격차 4.17퍼센트포인트 이내."
    ):
        "Experiment 12: router-cost is 95.2% cheaper than direct-premium "
        "(full precision), pass-rate gap within 4.17 percentage points.",
    # cost-vs-quality-scatter.svg
    "실험 12 · 비용 × 통과율 — Quality 모드는 비용이 더 들고 덜 풀었다":
        "Experiment 12 · cost × pass rate — Quality mode cost more and passed less",
    (
        "y축 확대(94–101%)로 4.17퍼센트포인트 격차 가시화 · "
        "x축 총비용(USD) · 실측 1회, directional"
    ):
        "y-axis zoomed (94–101%) to surface the 4.17 percentage point gap · x-axis "
        "total cost (USD) · one measured run, directional",
    "arm 총비용 (USD)": "Arm total cost (USD)",
    "direct-premium보다 비싸고 통과율 낮음":
        "Costs more and passes less than direct-premium",
    "→ 비용 높음 · ↓ 통과율 낮음": "→ higher cost · ↓ lower pass rate",
    # backend-distribution.svg
    "실험 12 · 백엔드 분포 — 각 arm이 실제로 도달한 모델":
        "Experiment 12 · backend distribution — the model each arm actually reached",
    (
        "채점된 셀만 · Cost 모드 100% Grok은 무효 처리된 실험 11과 "
        "실험 12에서 연속 재현 — 보장이 아니라 반복 관측"
    ):
        "Graded cells only · Cost mode 100% Grok repeated in experiment 11 "
        "(voided) and experiment 12 — a repeat, not a guarantee",
}

_HANGUL = re.compile(r"[\uac00-\ud7a3]")


def localize(ko_svg: str) -> str:
    """Return the English-labelled SVG for one committed Korean chart."""
    out = ko_svg
    for ko, en in LABELS.items():
        out = out.replace(ko, en)
    leftover = _HANGUL.findall(out)
    if leftover:
        # A label present in the chart is missing from LABELS; refuse to emit a
        # half-translated English asset.
        raise SystemExit(
            "localize_03d_svgs: unmapped Korean remains after substitution "
            f"({len(leftover)} char(s)); add the label to LABELS"
        )
    return out


def main() -> int:
    written = []
    for name in CHARTS:
        src = OUT_DIR / f"{name}.svg"
        if not src.is_file():
            raise SystemExit(f"localize_03d_svgs: missing source chart {src}")
        en = localize(src.read_text(encoding="utf-8"))
        dst = OUT_DIR / f"{name}.en.svg"
        dst.write_text(en, encoding="utf-8")
        written.append(dst)
        print(f"wrote {dst.relative_to(ROOT)}")
    return 0 if written else 1


if __name__ == "__main__":
    sys.exit(main())
