#!/usr/bin/env python3
"""Emit English ``.en.svg`` variants of the 03D result charts.

The charts in ``docs/assets/03d/*.svg`` are generated by
``build_03d_dashboard.py`` with Korean axis/legend/annotation labels baked in.
They are shared assets referenced by both the Korean and the English manual, so
an English page that embeds the bare ``.svg`` shows Korean chart labels to an
English reader (even though its Markdown alt-text is already English).

This script derives an English-labelled ``<name>.en.svg`` beside each Korean
``<name>.svg`` by substituting a fixed, audited Korean -> English label map.
It reads the *committed* Korean SVGs (it does **not** regenerate them, so the
Korean charts stay byte-identical and visually unchanged), and it fails loudly
if any chart carries a Korean run that the map does not cover — so a future
relabelling in ``build_03d_dashboard.py`` cannot silently leak Korean onto the
English pages. English wording follows the canonical English page
``docs/en/manual/03d-results.md`` (pass rate, cost-per-pass, sub-cent, full
precision, graded cells, the ``4.17%p`` notation, the section headings).

Run ``python scripts/localize_03d_svgs.py`` after regenerating the charts.
Numbers, model names and identifiers are never translated.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "docs" / "assets" / "03d"
CHARTS = (
    "arm-cost-comparison",
    "cost-vs-quality-scatter",
    "backend-distribution",
)

# Audited Korean -> English label map. Each key is a full text-node string that
# appears verbatim (and uniquely) in a committed chart; values keep every
# number, model name, symbol (× — · → ↓ –) and honesty term intact.
LABELS: dict[str, str] = {
    # arm-cost-comparison.svg
    "arm별 총비용 — 통과율 · cost-per-pass":
        "Total cost per arm — pass rate · cost-per-pass",
    "24 tasks × n=3 = 288 cells · 표시 금액 2자리(서브센트 4자리) · 절감은 풀정밀도 계산":
        "24 tasks × n=3 = 288 cells · amounts shown to 2 places (sub-cent to 4) "
        "· savings at full precision",
    "핵심 대비: router-cost는 direct-premium 대비 95.2% 저렴(풀정밀도), 품질 격차 4.17%p 이내.":
        "Key contrast: router-cost is 95.2% cheaper than direct-premium "
        "(full precision), pass-rate gap within 4.17%p.",
    # cost-vs-quality-scatter.svg
    "비용 × 품질 — quality 모드는 direct-premium에 지배당한다":
        "Cost × quality — the quality mode is dominated by direct-premium",
    "y축 확대(94–101%)로 4.17%p 격차 가시화 · x축 총비용(USD)":
        "y-axis zoomed (94–101%) to surface the 4.17%p gap · x-axis total cost (USD)",
    "arm 총비용 (USD)": "Arm total cost (USD)",
    "direct-premium 지배 영역": "direct-premium dominance region",
    "→ 더 비쌈 · ↓ 품질 낮음": "→ costlier · ↓ lower pass rate",
    # backend-distribution.svg
    "백엔드 분포 — arm별 실제 라우팅된 모델 (graded 셀 기준)":
        "Backend distribution — models actually routed per arm (graded cells)",
    "Cost 모드 100% Grok은 void 런과 이번 런 두 번 연속 재현됐다":
        "Cost mode 100% Grok, reproduced across the void run and this run "
        "(two consecutive)",
}

_HANGUL = re.compile(r"[\uac00-\ud7a3]")


def localize(ko_svg: str) -> str:
    """Return the English-labelled SVG for one committed Korean chart."""
    out = ko_svg
    for ko, en in LABELS.items():
        out = out.replace(ko, en)
    leftover = _HANGUL.findall(out)
    if leftover:
        # A label present in the chart is missing from LABELS; refuse to emit a
        # half-translated English asset.
        raise SystemExit(
            "localize_03d_svgs: unmapped Korean remains after substitution "
            f"({len(leftover)} char(s)); add the label to LABELS"
        )
    return out


def main() -> int:
    written = []
    for name in CHARTS:
        src = OUT_DIR / f"{name}.svg"
        if not src.is_file():
            raise SystemExit(f"localize_03d_svgs: missing source chart {src}")
        en = localize(src.read_text(encoding="utf-8"))
        dst = OUT_DIR / f"{name}.en.svg"
        dst.write_text(en, encoding="utf-8")
        written.append(dst)
        print(f"wrote {dst.relative_to(ROOT)}")
    return 0 if written else 1


if __name__ == "__main__":
    sys.exit(main())
